/** Public simulation API for application code and tests. */
export {
  ARRIVAL_DEMAND_ENGINE_INFLUENCES,
  advanceTick,
  adjustPlanPrice,
  adjustPlanPurchase,
  buyEquipment,
  buyImprovement,
  candidatePoolForDay,
  closeDay,
  continueEndless,
  createCampaign,
  demandRate,
  dispatchGameCommand,
  equipmentPreparationMultiplier,
  hireStaff,
  MAX_REPORT_CHARGE_GROUPS,
  MAX_REPORT_CHARGE_PRICE_CENTS,
  MIN_REPORT_CHARGE_PRICE_CENTS,
  operationalEffects,
  prepareDay,
  promoteVenue,
  purchaseCost,
  resolveEvent,
  serviceQueueCapacity,
  setRushSpeed,
  staffRoleOperationalEffect,
  startNextDay,
  startRush,
  togglePause,
} from './engine';
export {
  DEPARTMENT_WORKLOAD_DELAYS,
  STAFF_ROLES,
  STAFF_ROLE_DETAILS,
  STAFF_ROLE_LABELS,
  VENUE_WORKFORCE_CAPACITY,
  staffRoleAvailableAtVenue,
  workforceCapacityFor,
} from '../content/gameContent';
export { GameRuleError } from './errors';
export {
  CANDIDATES_PER_DAY,
  LEGACY_STAFF_NAMES,
  MAX_STAFF_NAME_DAY,
  RESERVED_STAFF_NAME_COUNT,
  STAFF_NAME_NAMESPACE_SIZE,
  STAFF_NAMES_PER_TIER,
  SUPPORTED_CANDIDATE_NAME_COUNT,
  candidateStaffId,
  candidateStaffName,
  candidateStaffOrdinal,
  candidateStaffSlotFromId,
  reservedStaffName,
  staffNameAtOrdinal,
} from './staffNames';
export {
  baseDrinkChoiceWeight,
  drinkWeatherChoiceMultiplier,
  milkForDraw,
  milkProbabilities,
  ORDER_CHOICE_DEMAND_ENGINE_INFLUENCES,
  segmentForDraw,
  sizeForDraw,
  sizeProbabilities,
} from './demandModel';
export {
  applyDemandInfluence,
  DEMAND_INFLUENCES,
  DEMAND_INFLUENCE_IDS,
  DIFFICULTY_DEVIATION_MULTIPLIERS,
} from './demandInfluences';
export type {
  ArrivalDemandInfluenceId,
  DemandInfluenceApplication,
  DemandInfluenceDefinition,
  DemandInfluenceDomain,
  DemandInfluenceId,
  OrderChoiceDemandInfluenceId,
} from './demandInfluences';
export { formatIngredientQuantity, ingredientCapacities, weightedIngredientUse } from './capacity';
export type { IngredientCapacity } from './capacity';
export {
  activeServiceJobs,
  assignedStaffIds,
  defaultStationAssignments,
  emptyExpressStartCounters,
  emptyServiceAggregates,
  emptyServiceJobs,
  emptyStationAssignments,
  expressDrinkEligible,
  expressEligibleDrinkIds,
  laneForDrink,
  LANE_IDS,
  MAX_CONSECUTIVE_EXPRESS_STARTS,
  MAX_EXPRESS_DRINKS,
  MAX_SERVICE_JOBS_PER_RUSH,
  serviceAggregatesForPlan,
  serviceConfigFor,
  serviceJobId,
  STAFF_STATION_COMPATIBILITY,
  staffStationCompatible,
  STATION_DETAILS,
  STATION_EQUIPMENT_IDS,
  STATION_IDS,
  stationForDrink,
  stationReadyForService,
  VENUE_SERVICE_CONFIG,
  waitingCustomers,
} from './serviceStations';
export type { StationConfig, VenueServiceConfig } from './serviceStations';
export { ACHIEVEMENT_DETAILS, recordCampaignOutcome } from './meta';
export {
  addPlannedPurchases,
  batchExpiryDay,
  completeIngredientTotals,
  consumeIngredientsAtServiceStart,
  consumeIngredientsLifo,
  earliestInventoryExpiry,
  expireInventoryAfterRush,
  extendInventoryRefrigeration,
  hasIngredients,
  ingredientQuantity,
  inventoryFromLegacyTotals,
  inventoryTotals,
  plannedPurchaseTotals,
  refrigerationExtensionDays,
} from './inventory';
export {
  campaignRecordsByDifficulty,
  canOpen,
  completedSaleLabel,
  describeRushActivity,
  DIFFICULTY_DESCRIPTIONS,
  DIFFICULTY_LABELS,
  formatMoney,
  rushClock,
  selectedSupplyCost,
  serviceFlowSummary,
  staffRoleValue,
  stockedInventory,
  venueLabel,
  workforceAppliedEffectLabels,
} from './selectors';
export type * from './types';
